version: "3.7"
services: 
  database:
    container_name: p_database
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: p_db
      MYSQL_USER: p_user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql