version: "3.7"
services: 
  database:
    container_name: database
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: m_manager
      MYSQL_USER: m_manager
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql